import { Food } from './types';

export const FOOD_DATABASE: Food[] = [
  { id: '1', name: 'Riz blanc (cru)', englishName: 'White rice (raw)', emoji: '🍚', calories: 350, protein: 7.1, fat: 0.6, carbs: 79.0, servingSize: '100g', type: 'solid' },
  { id: '2', name: 'Riz blanc (cuit)', englishName: 'White rice (cooked)', emoji: '🍚', calories: 130, protein: 2.7, fat: 0.3, carbs: 28.6, servingSize: '100g', type: 'solid' },
  { id: '3', name: 'Pâtes (crues)', englishName: 'Pasta (raw)', emoji: '🍝', calories: 350, protein: 12.5, fat: 1.5, carbs: 72.2, servingSize: '100g', type: 'solid' },
  { id: '4', name: 'Pâtes (cuites)', englishName: 'Pasta (cooked)', emoji: '🍝', calories: 150, protein: 5.8, fat: 0.9, carbs: 30.9, servingSize: '100g', type: 'solid' },
  { id: '5', name: 'Blanc de poulet', englishName: 'Chicken breast', emoji: '🍗', calories: 110, protein: 31.0, fat: 3.6, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '6', name: 'Boeuf haché 5%', englishName: 'Ground beef 5%', emoji: '🥩', calories: 125, protein: 21.5, fat: 5.0, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '7', name: 'Oeuf (entier)', englishName: 'Egg (whole)', emoji: '🥚', calories: 143, protein: 12.6, fat: 9.5, carbs: 0.7, servingSize: '1 unit (50g)', type: 'unit', weightPerUnit: 50 },
  { id: '8', name: 'Saumon', englishName: 'Salmon', emoji: '🐟', calories: 208, protein: 20.0, fat: 13.0, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '9', name: 'Thon en boîte (eau)', englishName: 'Canned tuna (water)', emoji: '🥫', calories: 110, protein: 25.5, fat: 0.5, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '10', name: 'Pain de mie (Tranche)', englishName: 'Sliced bread (slice)', emoji: '🍞', calories: 260, protein: 8.0, fat: 3.2, carbs: 49.0, servingSize: '1 slice (35g)', type: 'unit', weightPerUnit: 35 },
  { id: '11', name: 'Baguette tradition', englishName: 'Traditional baguette', emoji: '🥖', calories: 270, protein: 8.5, fat: 1.5, carbs: 55.0, servingSize: '1 unit (250g)', type: 'unit', weightPerUnit: 250 },
  { id: '12', name: 'Avoine (Flocons)', englishName: 'Rolled oats', emoji: '🥣', calories: 370, protein: 13.2, fat: 6.9, carbs: 67.0, servingSize: '100g', type: 'solid' },
  { id: '13', name: 'Lait demi-écrémé', englishName: 'Semi-skimmed milk', emoji: '🥛', calories: 47, protein: 3.6, fat: 1.6, carbs: 4.7, servingSize: '100ml', type: 'liquid' },
  { id: '14', name: 'Fromage blanc 0%', englishName: 'Fat-free fromage blanc', emoji: '🥄', calories: 48, protein: 7.5, fat: 0.2, carbs: 4.0, servingSize: '100g', type: 'solid' },
  { id: '15', name: 'Beurre de cacahuète', englishName: 'Peanut butter', emoji: '🥜', calories: 588, protein: 25.1, fat: 50.4, carbs: 20.1, servingSize: '100g', type: 'solid' },
  { id: '16', name: 'Amandes', englishName: 'Almonds', emoji: '🌰', calories: 579, protein: 21.2, fat: 49.9, carbs: 21.6, servingSize: '100g', type: 'solid' },
  { id: '17', name: 'Huile d\'olive', englishName: 'Olive oil', emoji: '🫒', calories: 900, protein: 0.0, fat: 100.0, carbs: 0.0, servingSize: '100ml', type: 'liquid' },
  { id: '18', name: 'Pomme', englishName: 'Apple', emoji: '🍎', calories: 52, protein: 0.3, fat: 0.2, carbs: 13.8, servingSize: '1 unit (150g)', type: 'unit', weightPerUnit: 150 },
  { id: '19', name: 'Banane', englishName: 'Banana', emoji: '🍌', calories: 89, protein: 1.1, fat: 0.3, carbs: 23.0, servingSize: '1 unit (120g)', type: 'unit', weightPerUnit: 120 },
  { id: '20', name: 'Avocat', englishName: 'Avocado', emoji: '🥑', calories: 160, protein: 2.0, fat: 14.7, carbs: 8.5, servingSize: '1 unit (150g)', type: 'unit', weightPerUnit: 150 },
  { id: '21', name: 'Brocoli', englishName: 'Broccoli', emoji: '🥦', calories: 34, protein: 2.8, fat: 0.4, carbs: 7.0, servingSize: '100g', type: 'solid' },
  { id: '22', name: 'Carotte', englishName: 'Carrot', emoji: '🥕', calories: 41, protein: 0.9, fat: 0.2, carbs: 9.6, servingSize: '1 unit (100g)', type: 'unit', weightPerUnit: 100 },
  { id: '23', name: 'Pomme de terre', englishName: 'Potato', emoji: '🥔', calories: 80, protein: 2.0, fat: 0.1, carbs: 17.5, servingSize: '1 unit (150g)', type: 'unit', weightPerUnit: 150 },
  { id: '24', name: 'Tomate', englishName: 'Tomato', emoji: '🍅', calories: 18, protein: 0.9, fat: 0.2, carbs: 3.9, servingSize: '1 unit (120g)', type: 'unit', weightPerUnit: 120 },
  { id: '25', name: 'Concombre', englishName: 'Cucumber', emoji: '🥒', calories: 15, protein: 0.7, fat: 0.1, carbs: 3.6, servingSize: '1 unit (400g)', type: 'unit', weightPerUnit: 400 },
  { id: '26', name: 'Salade', englishName: 'Salad', emoji: '🥗', calories: 15, protein: 1.4, fat: 0.2, carbs: 2.9, servingSize: '100g', type: 'solid' },
  { id: '27', name: 'Miel', englishName: 'Honey', emoji: '🍯', calories: 304, protein: 0.3, fat: 0.0, carbs: 82.4, servingSize: '100g', type: 'solid' },
  { id: '28', name: 'Sucre blanc', englishName: 'White sugar', emoji: '🧂', calories: 387, protein: 0.0, fat: 0.0, carbs: 100.0, servingSize: '100g', type: 'solid' },
  { id: '29', name: 'Ketchup', englishName: 'Ketchup', emoji: '🍅', calories: 100, protein: 1.7, fat: 0.1, carbs: 26.1, servingSize: '100g', type: 'solid' },
  { id: '30', name: 'Mayonnaise', englishName: 'Mayonnaise', emoji: '🥚', calories: 680, protein: 1.3, fat: 74.9, carbs: 1.5, servingSize: '100g', type: 'solid' },
  { id: '31', name: 'Chocolat noir 70%', englishName: 'Dark chocolate 70%', emoji: '🍫', calories: 598, protein: 8.0, fat: 42.6, carbs: 45.9, servingSize: '100g', type: 'solid' },
  { id: '32', name: 'Croissant', englishName: 'Croissant', emoji: '🥐', calories: 406, protein: 8.2, fat: 20.9, carbs: 47.5, servingSize: '1 unit (50g)', type: 'unit', weightPerUnit: 50 },
  { id: '33', name: 'Pizza (Part moyenne)', englishName: 'Pizza (Medium slice)', emoji: '🍕', calories: 220, protein: 11.0, fat: 10.0, carbs: 30.0, servingSize: '1 slice (150g)', type: 'unit', weightPerUnit: 150 },
  { id: '34', name: 'Burger (Fast food)', englishName: 'Burger (Fast food)', emoji: '🍔', calories: 260, protein: 14.5, fat: 14.2, carbs: 25.0, servingSize: '1 unit (220g)', type: 'unit', weightPerUnit: 220 },
  { id: '35', name: 'Frites (Portion)', englishName: 'French fries (Portion)', emoji: '🍟', calories: 312, protein: 3.4, fat: 15.0, carbs: 41.4, servingSize: '1 portion (115g)', type: 'unit', weightPerUnit: 115 },
  { id: '36', name: 'Coca-Cola', englishName: 'Coca-Cola', emoji: '🥤', calories: 42, protein: 0.0, fat: 0.0, carbs: 10.6, servingSize: '100ml', type: 'liquid' },
  { id: '37', name: 'Jus d\'orange', englishName: 'Orange juice', emoji: '🧃', calories: 45, protein: 0.7, fat: 0.2, carbs: 10.4, servingSize: '100ml', type: 'liquid' },
  { id: '38', name: 'Bière', englishName: 'Beer', emoji: '🍺', calories: 43, protein: 0.5, fat: 0.0, carbs: 3.6, servingSize: '100ml', type: 'liquid' },
  { id: '39', name: 'Vin rouge', englishName: 'Red wine', emoji: '🍷', calories: 85, protein: 0.1, fat: 0.0, carbs: 2.6, servingSize: '100ml', type: 'liquid' },
  { id: '40', name: 'Café noir (sans sucre)', englishName: 'Black coffee (no sugar)', emoji: '☕', calories: 2, protein: 0.1, fat: 0.0, carbs: 0.0, servingSize: '100ml', type: 'liquid' },
  { id: '41', name: 'Fraise', englishName: 'Strawberry', emoji: '🍓', calories: 32, protein: 0.7, fat: 0.3, carbs: 7.7, servingSize: '100g', type: 'solid' },
  { id: '42', name: 'Framboise', englishName: 'Raspberry', emoji: '🫐', calories: 52, protein: 1.2, fat: 0.7, carbs: 11.9, servingSize: '100g', type: 'solid' },
  { id: '43', name: 'Myrtille', englishName: 'Blueberry', emoji: '🫐', calories: 57, protein: 0.7, fat: 0.3, carbs: 14.5, servingSize: '100g', type: 'solid' },
  { id: '44', name: 'Mûre', englishName: 'Blackberry', emoji: '🫐', calories: 43, protein: 1.4, fat: 0.5, carbs: 9.6, servingSize: '100g', type: 'solid' },
  { id: '45', name: 'Pêche', englishName: 'Peach', emoji: '🍑', calories: 39, protein: 0.9, fat: 0.3, carbs: 9.5, servingSize: '1 unit (150g)', type: 'unit', weightPerUnit: 150 },
  { id: '46', name: 'Abricot', englishName: 'Apricot', emoji: '🍑', calories: 48, protein: 1.4, fat: 0.4, carbs: 11.1, servingSize: '1 unit (45g)', type: 'unit', weightPerUnit: 45 },
  { id: '47', name: 'Prune', englishName: 'Plum', emoji: '🫐', calories: 46, protein: 0.7, fat: 0.3, carbs: 11.4, servingSize: '1 unit (60g)', type: 'unit', weightPerUnit: 60 },
  { id: '48', name: 'Cerise', englishName: 'Cherry', emoji: '🍒', calories: 50, protein: 1.1, fat: 0.2, carbs: 12.8, servingSize: '100g', type: 'solid' },
  { id: '49', name: 'Ananas', englishName: 'Pineapple', emoji: '🍍', calories: 50, protein: 0.5, fat: 0.1, carbs: 13.1, servingSize: '100g', type: 'solid' },
  { id: '50', name: 'Mangue', englishName: 'Mango', emoji: '🥭', calories: 60, protein: 0.8, fat: 0.4, carbs: 15.0, servingSize: '1 unit (300g)', type: 'unit', weightPerUnit: 300 },
  { id: '51', name: 'Kiwi', englishName: 'Kiwi', emoji: '🥝', calories: 61, protein: 1.1, fat: 0.5, carbs: 14.7, servingSize: '1 unit (75g)', type: 'unit', weightPerUnit: 75 },
  { id: '52', name: 'Papaye', englishName: 'Papaya', emoji: '🥭', calories: 43, protein: 0.5, fat: 0.3, carbs: 10.8, servingSize: '1 unit (400g)', type: 'unit', weightPerUnit: 400 },
  { id: '53', name: 'Melon', englishName: 'Melon', emoji: '🍈', calories: 34, protein: 0.8, fat: 0.2, carbs: 8.2, servingSize: '100g', type: 'solid' },
  { id: '54', name: 'Pastèque', englishName: 'Watermelon', emoji: '🍉', calories: 30, protein: 0.6, fat: 0.2, carbs: 7.6, servingSize: '100g', type: 'solid' },
  { id: '55', name: 'Poire', englishName: 'Pear', emoji: '🍐', calories: 57, protein: 0.4, fat: 0.1, carbs: 15.5, servingSize: '1 unit (150g)', type: 'unit', weightPerUnit: 150 },
  { id: '56', name: 'Citron', englishName: 'Lemon', emoji: '🍋', calories: 29, protein: 1.1, fat: 0.3, carbs: 9.3, servingSize: '1 unit (100g)', type: 'unit', weightPerUnit: 100 },
  { id: '57', name: 'Citron vert', englishName: 'Lime', emoji: '🍋', calories: 30, protein: 0.7, fat: 0.2, carbs: 10.5, servingSize: '1 unit (50g)', type: 'unit', weightPerUnit: 50 },
  { id: '58', name: 'Pamplemousse', englishName: 'Grapefruit', emoji: '🍊', calories: 42, protein: 0.8, fat: 0.1, carbs: 10.7, servingSize: '1 unit (250g)', type: 'unit', weightPerUnit: 250 },
  { id: '59', name: 'Orange', englishName: 'Orange', emoji: '🍊', calories: 47, protein: 0.9, fat: 0.1, carbs: 11.8, servingSize: '1 unit (130g)', type: 'unit', weightPerUnit: 130 },
  { id: '60', name: 'Raisin', englishName: 'Grape', emoji: '🍇', calories: 69, protein: 0.7, fat: 0.2, carbs: 18.1, servingSize: '100g', type: 'solid' },
  { id: '61', name: 'Épinard', englishName: 'Spinach', emoji: '🥬', calories: 23, protein: 2.9, fat: 0.4, carbs: 3.6, servingSize: '100g', type: 'solid' },
  { id: '62', name: 'Courgette', englishName: 'Zucchini', emoji: '🥒', calories: 17, protein: 1.2, fat: 0.3, carbs: 3.1, servingSize: '1 unit (200g)', type: 'unit', weightPerUnit: 200 },
  { id: '63', name: 'Aubergine', englishName: 'Eggplant', emoji: '🍆', calories: 25, protein: 1.0, fat: 0.2, carbs: 5.7, servingSize: '1 unit (250g)', type: 'unit', weightPerUnit: 250 },
  { id: '64', name: 'Poivron rouge', englishName: 'Red bell pepper', emoji: '🫑', calories: 31, protein: 1.0, fat: 0.3, carbs: 6.0, servingSize: '1 unit (150g)', type: 'unit', weightPerUnit: 150 },
  { id: '65', name: 'Poivron vert', englishName: 'Green bell pepper', emoji: '🫑', calories: 20, protein: 0.9, fat: 0.2, carbs: 4.6, servingSize: '1 unit (150g)', type: 'unit', weightPerUnit: 150 },
  { id: '66', name: 'Chou-fleur', englishName: 'Cauliflower', emoji: '🥦', calories: 25, protein: 1.9, fat: 0.3, carbs: 5.0, servingSize: '100g', type: 'solid' },
  { id: '67', name: 'Haricots verts', englishName: 'Green beans', emoji: '🫘', calories: 31, protein: 1.8, fat: 0.2, carbs: 7.1, servingSize: '100g', type: 'solid' },
  { id: '68', name: 'Petits pois', englishName: 'Peas', emoji: '🫛', calories: 81, protein: 5.4, fat: 0.4, carbs: 14.5, servingSize: '100g', type: 'solid' },
  { id: '69', name: 'Asperge', englishName: 'Asparagus', emoji: '🥬', calories: 20, protein: 2.2, fat: 0.2, carbs: 3.9, servingSize: '100g', type: 'solid' },
  { id: '70', name: 'Chou blanc', englishName: 'White cabbage', emoji: '🥬', calories: 25, protein: 1.3, fat: 0.1, carbs: 5.8, servingSize: '100g', type: 'solid' },
  { id: '71', name: 'Choux de Bruxelles', englishName: 'Brussels sprouts', emoji: '🥬', calories: 43, protein: 3.4, fat: 0.3, carbs: 9.0, servingSize: '100g', type: 'solid' },
  { id: '72', name: 'Oignon', englishName: 'Onion', emoji: '🧅', calories: 40, protein: 1.1, fat: 0.1, carbs: 9.3, servingSize: '1 unit (100g)', type: 'unit', weightPerUnit: 100 },
  { id: '73', name: 'Ail', englishName: 'Garlic', emoji: '🧄', calories: 149, protein: 6.4, fat: 0.5, carbs: 33.1, servingSize: '1 clove (5g)', type: 'unit', weightPerUnit: 5 },
  { id: '74', name: 'Poireau', englishName: 'Leek', emoji: '🥬', calories: 61, protein: 1.5, fat: 0.3, carbs: 14.2, servingSize: '1 unit (150g)', type: 'unit', weightPerUnit: 150 },
  { id: '75', name: 'Champignon de Paris', englishName: 'White mushroom', emoji: '🍄', calories: 22, protein: 3.1, fat: 0.3, carbs: 3.3, servingSize: '100g', type: 'solid' },
  { id: '76', name: 'Patate douce', englishName: 'Sweet potato', emoji: '🍠', calories: 86, protein: 1.6, fat: 0.1, carbs: 20.1, servingSize: '1 unit (200g)', type: 'unit', weightPerUnit: 200 },
  { id: '77', name: 'Citrouille', englishName: 'Pumpkin', emoji: '🎃', calories: 26, protein: 1.0, fat: 0.1, carbs: 6.5, servingSize: '100g', type: 'solid' },
  { id: '78', name: 'Courge Butternut', englishName: 'Butternut squash', emoji: '🎃', calories: 45, protein: 1.0, fat: 0.1, carbs: 11.7, servingSize: '100g', type: 'solid' },
  { id: '79', name: 'Radis', englishName: 'Radish', emoji: '🥗', calories: 16, protein: 0.7, fat: 0.1, carbs: 3.4, servingSize: '100g', type: 'solid' },
  { id: '80', name: 'Navet', englishName: 'Turnip', emoji: '🧅', calories: 28, protein: 0.9, fat: 0.1, carbs: 6.4, servingSize: '1 unit (100g)', type: 'unit', weightPerUnit: 100 },
  { id: '81', name: 'Betterave', englishName: 'Beetroot', emoji: '🥗', calories: 43, protein: 1.7, fat: 0.1, carbs: 10.0, servingSize: '1 unit (150g)', type: 'unit', weightPerUnit: 150 },
  { id: '82', name: 'Céleri', englishName: 'Celery', emoji: '🥬', calories: 16, protein: 0.7, fat: 0.2, carbs: 3.0, servingSize: '100g', type: 'solid' },
  { id: '83', name: 'Artichaut', englishName: 'Artichoke', emoji: '🥗', calories: 47, protein: 3.3, fat: 0.2, carbs: 10.5, servingSize: '1 unit (120g)', type: 'unit', weightPerUnit: 120 },
  { id: '84', name: 'Maïs doux', englishName: 'Sweet corn', emoji: '🌽', calories: 86, protein: 3.3, fat: 1.2, carbs: 19.0, servingSize: '100g', type: 'solid' },
  { id: '85', name: 'Endive', englishName: 'Endive', emoji: '🥬', calories: 17, protein: 1.7, fat: 0.2, carbs: 3.4, servingSize: '1 unit (150g)', type: 'unit', weightPerUnit: 150 },
  { id: '86', name: 'Fenouil', englishName: 'Fennel', emoji: '🥬', calories: 31, protein: 1.2, fat: 0.2, carbs: 7.3, servingSize: '1 unit (200g)', type: 'unit', weightPerUnit: 200 },
  { id: '87', name: 'Blanc de dinde', englishName: 'Turkey breast', emoji: '🦃', calories: 104, protein: 29.0, fat: 1.0, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '88', name: 'Magret de canard', englishName: 'Duck breast', emoji: '🦆', calories: 337, protein: 19.0, fat: 28.0, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '89', name: 'Côte de porc', englishName: 'Pork chop', emoji: '🍖', calories: 231, protein: 22.0, fat: 16.0, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '90', name: 'Bacon', englishName: 'Bacon', emoji: '🥓', calories: 541, protein: 37.0, fat: 42.0, carbs: 1.4, servingSize: '100g', type: 'solid' },
  { id: '91', name: 'Jambon blanc', englishName: 'Ham', emoji: '🥓', calories: 110, protein: 17.0, fat: 4.5, carbs: 1.5, servingSize: '1 slice (40g)', type: 'unit', weightPerUnit: 40 },
  { id: '92', name: 'Saucisse de Toulouse', englishName: 'Toulouse sausage', emoji: '🌭', calories: 310, protein: 15.0, fat: 26.0, carbs: 2.0, servingSize: '1 unit (100g)', type: 'unit', weightPerUnit: 100 },
  { id: '93', name: 'Saucisse de Francfort', englishName: 'Frankfurter', emoji: '🌭', calories: 290, protein: 11.0, fat: 25.0, carbs: 2.0, servingSize: '1 unit (35g)', type: 'unit', weightPerUnit: 35 },
  { id: '94', name: 'Côtelette d\'agneau', englishName: 'Lamb chop', emoji: '🍖', calories: 294, protein: 20.0, fat: 23.0, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '95', name: 'Escalope de veau', englishName: 'Veal escalope', emoji: '🥩', calories: 105, protein: 21.5, fat: 2.5, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '96', name: 'Chorizo', englishName: 'Chorizo', emoji: '🥩', calories: 455, protein: 24.1, fat: 38.3, carbs: 1.9, servingSize: '100g', type: 'solid' },
  { id: '97', name: 'Salami', englishName: 'Salami', emoji: '🥓', calories: 336, protein: 22.6, fat: 25.7, carbs: 2.0, servingSize: '100g', type: 'solid' },
  { id: '98', name: 'Jambon cru (Prosciutto)', englishName: 'Prosciutto', emoji: '🥓', calories: 230, protein: 25.9, fat: 14.0, carbs: 0.3, servingSize: '1 slice (15g)', type: 'unit', weightPerUnit: 15 },
  { id: '99', name: 'Cuisse de poulet', englishName: 'Chicken thigh', emoji: '🍗', calories: 177, protein: 20.0, fat: 11.0, carbs: 0.0, servingSize: '1 unit (150g)', type: 'unit', weightPerUnit: 150 },
  { id: '100', name: 'Rosbif', englishName: 'Roast beef', emoji: '🥩', calories: 152, protein: 26.5, fat: 5.5, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '101', name: 'Entrecôte', englishName: 'Ribeye steak', emoji: '🥩', calories: 291, protein: 20.0, fat: 22.0, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '102', name: 'Cabillaud', englishName: 'Cod', emoji: '🐟', calories: 82, protein: 17.8, fat: 0.7, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '103', name: 'Églefin', englishName: 'Haddock', emoji: '🐟', calories: 90, protein: 19.0, fat: 0.9, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '104', name: 'Truite', englishName: 'Trout', emoji: '🐟', calories: 148, protein: 20.0, fat: 5.0, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '105', name: 'Sardines à l\'huile', englishName: 'Sardines in oil', emoji: '🐟', calories: 208, protein: 24.6, fat: 11.5, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '106', name: 'Maquereau', englishName: 'Mackerel', emoji: '🐟', calories: 305, protein: 18.6, fat: 24.5, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '107', name: 'Crevette', englishName: 'Shrimp', emoji: '🦐', calories: 99, protein: 20.3, fat: 1.7, carbs: 0.9, servingSize: '100g', type: 'solid' },
  { id: '108', name: 'Crabe', englishName: 'Crab', emoji: '🦀', calories: 97, protein: 18.1, fat: 1.1, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '109', name: 'Homard', englishName: 'Lobster', emoji: '🦞', calories: 89, protein: 19.0, fat: 0.9, carbs: 0.5, servingSize: '100g', type: 'solid' },
  { id: '110', name: 'Moule', englishName: 'Mussel', emoji: '🦪', calories: 86, protein: 11.9, fat: 2.2, carbs: 3.7, servingSize: '100g', type: 'solid' },
  { id: '111', name: 'Huître', englishName: 'Oyster', emoji: '🦪', calories: 68, protein: 7.1, fat: 2.5, carbs: 4.5, servingSize: '1 unit (15g)', type: 'unit', weightPerUnit: 15 },
  { id: '112', name: 'Saint-Jacques', englishName: 'Scallop', emoji: '🦪', calories: 111, protein: 20.5, fat: 0.8, carbs: 3.2, servingSize: '100g', type: 'solid' },
  { id: '113', name: 'Calamar', englishName: 'Squid', emoji: '🦑', calories: 92, protein: 15.6, fat: 1.4, carbs: 3.1, servingSize: '100g', type: 'solid' },
  { id: '114', name: 'Poulpe', englishName: 'Octopus', emoji: '🐙', calories: 164, protein: 14.9, fat: 1.0, carbs: 3.7, servingSize: '100g', type: 'solid' },
  { id: '115', name: 'Anchois', englishName: 'Anchovy', emoji: '🐟', calories: 210, protein: 20.4, fat: 12.6, carbs: 0.3, servingSize: '100g', type: 'solid' },
  { id: '116', name: 'Beurre doux', englishName: 'Unsalted butter', emoji: '🧈', calories: 717, protein: 0.7, fat: 81.1, carbs: 0.6, servingSize: '100g', type: 'solid' },
  { id: '117', name: 'Crème fraîche entière', englishName: 'Heavy cream', emoji: '🥄', calories: 340, protein: 2.1, fat: 35.0, carbs: 2.8, servingSize: '100ml', type: 'liquid' },
  { id: '118', name: 'Crème aigre', englishName: 'Sour cream', emoji: '🥄', calories: 198, protein: 2.1, fat: 19.4, carbs: 3.8, servingSize: '100ml', type: 'liquid' },
  { id: '119', name: 'Cheddar', englishName: 'Cheddar', emoji: '🧀', calories: 402, protein: 25.0, fat: 33.1, carbs: 1.3, servingSize: '100g', type: 'solid' },
  { id: '120', name: 'Mozzarella', englishName: 'Mozzarella', emoji: '🧀', calories: 280, protein: 22.2, fat: 17.4, carbs: 2.2, servingSize: '100g', type: 'solid' },
  { id: '121', name: 'Parmesan', englishName: 'Parmesan', emoji: '🧀', calories: 431, protein: 35.8, fat: 29.7, carbs: 3.2, servingSize: '100g', type: 'solid' },
  { id: '122', name: 'Brie', englishName: 'Brie', emoji: '🧀', calories: 334, protein: 20.8, fat: 27.7, carbs: 0.5, servingSize: '100g', type: 'solid' },
  { id: '123', name: 'Camembert', englishName: 'Camembert', emoji: '🧀', calories: 300, protein: 19.8, fat: 24.3, carbs: 0.5, servingSize: '100g', type: 'solid' },
  { id: '124', name: 'Roquefort', englishName: 'Roquefort', emoji: '🧀', calories: 369, protein: 21.5, fat: 30.6, carbs: 2.0, servingSize: '100g', type: 'solid' },
  { id: '125', name: 'Fromage de chèvre', englishName: 'Goat cheese', emoji: '🧀', calories: 364, protein: 21.6, fat: 29.8, carbs: 2.0, servingSize: '100g', type: 'solid' },
  { id: '126', name: 'Feta', englishName: 'Feta', emoji: '🧀', calories: 264, protein: 14.2, fat: 21.3, carbs: 4.1, servingSize: '100g', type: 'solid' },
  { id: '127', name: 'Emmental', englishName: 'Emmental', emoji: '🧀', calories: 380, protein: 28.0, fat: 29.0, carbs: 1.5, servingSize: '100g', type: 'solid' },
  { id: '128', name: 'Gouda', englishName: 'Gouda', emoji: '🧀', calories: 356, protein: 25.0, fat: 27.4, carbs: 2.2, servingSize: '100g', type: 'solid' },
  { id: '129', name: 'Yaourt grec', englishName: 'Greek yogurt', emoji: '🥣', calories: 97, protein: 9.0, fat: 5.0, carbs: 3.6, servingSize: '100g', type: 'solid' },
  { id: '130', name: 'Skyr', englishName: 'Skyr', emoji: '🥄', calories: 57, protein: 11.0, fat: 0.2, carbs: 4.0, servingSize: '100g', type: 'solid' },
  { id: '131', name: 'Lait entier', englishName: 'Whole milk', emoji: '🥛', calories: 61, protein: 3.2, fat: 3.6, carbs: 4.6, servingSize: '100ml', type: 'liquid' },
  { id: '132', name: 'Lait écrémé', englishName: 'Skimmed milk', emoji: '🥛', calories: 34, protein: 3.4, fat: 0.2, carbs: 5.0, servingSize: '100ml', type: 'liquid' },
  { id: '133', name: 'Riz complet (cru)', englishName: 'Brown rice (raw)', emoji: '🍚', calories: 370, protein: 7.5, fat: 2.7, carbs: 77.2, servingSize: '100g', type: 'solid' },
  { id: '134', name: 'Riz complet (cuit)', englishName: 'Brown rice (cooked)', emoji: '🍚', calories: 111, protein: 2.6, fat: 0.9, carbs: 23.0, servingSize: '100g', type: 'solid' },
  { id: '135', name: 'Quinoa (cru)', englishName: 'Quinoa (raw)', emoji: '🥣', calories: 368, protein: 14.1, fat: 6.1, carbs: 64.2, servingSize: '100g', type: 'solid' },
  { id: '136', name: 'Quinoa (cuit)', englishName: 'Quinoa (cooked)', emoji: '🥣', calories: 120, protein: 4.4, fat: 1.9, carbs: 21.3, servingSize: '100g', type: 'solid' },
  { id: '137', name: 'Semoule de couscous (crue)', englishName: 'Couscous semolina (raw)', emoji: '🍲', calories: 376, protein: 12.8, fat: 1.1, carbs: 77.4, servingSize: '100g', type: 'solid' },
  { id: '138', name: 'Semoule de couscous (cuite)', englishName: 'Couscous semolina (cooked)', emoji: '🍲', calories: 112, protein: 3.8, fat: 0.2, carbs: 23.2, servingSize: '100g', type: 'solid' },
  { id: '139', name: 'Lentilles (crues)', englishName: 'Lentils (raw)', emoji: '🧆', calories: 353, protein: 25.8, fat: 1.1, carbs: 60.1, servingSize: '100g', type: 'solid' },
  { id: '140', name: 'Lentilles (cuites)', englishName: 'Lentils (cooked)', emoji: '🧆', calories: 116, protein: 9.0, fat: 0.4, carbs: 20.1, servingSize: '100g', type: 'solid' },
  { id: '141', name: 'Pois chiches (en boîte)', englishName: 'Chickpeas (canned)', emoji: '🧆', calories: 139, protein: 7.2, fat: 2.6, carbs: 22.5, servingSize: '100g', type: 'solid' },
  { id: '142', name: 'Haricots noirs', englishName: 'Black beans', emoji: '🫘', calories: 132, protein: 8.9, fat: 0.5, carbs: 23.7, servingSize: '100g', type: 'solid' },
  { id: '143', name: 'Haricots rouges', englishName: 'Kidney beans', emoji: '🫘', calories: 127, protein: 8.7, fat: 0.5, carbs: 22.8, servingSize: '100g', type: 'solid' },
  { id: '144', name: 'Noix', englishName: 'Walnuts', emoji: '🌰', calories: 654, protein: 15.2, fat: 65.2, carbs: 13.7, servingSize: '100g', type: 'solid' },
  { id: '145', name: 'Noix de cajou', englishName: 'Cashews', emoji: '🥜', calories: 553, protein: 18.2, fat: 43.9, carbs: 30.2, servingSize: '100g', type: 'solid' },
  { id: '146', name: 'Pistaches', englishName: 'Pistachios', emoji: '🥜', calories: 562, protein: 20.2, fat: 45.4, carbs: 27.2, servingSize: '100g', type: 'solid' },
  { id: '147', name: 'Noix de pécan', englishName: 'Pecans', emoji: '🌰', calories: 691, protein: 9.2, fat: 72.0, carbs: 13.9, servingSize: '100g', type: 'solid' },
  { id: '148', name: 'Noisettes', englishName: 'Hazelnuts', emoji: '🌰', calories: 628, protein: 14.1, fat: 60.8, carbs: 16.7, servingSize: '100g', type: 'solid' },
  { id: '149', name: 'Noix de macadamia', englishName: 'Macadamia nuts', emoji: '🌰', calories: 718, protein: 7.9, fat: 75.8, carbs: 13.8, servingSize: '100g', type: 'solid' },
  { id: '150', name: 'Graines de tournesol', englishName: 'Sunflower seeds', emoji: '🌻', calories: 584, protein: 20.8, fat: 51.5, carbs: 20.0, servingSize: '100g', type: 'solid' },
  { id: '151', name: 'Graines de chia', englishName: 'Chia seeds', emoji: '🫙', calories: 486, protein: 16.5, fat: 30.7, carbs: 42.1, servingSize: '100g', type: 'solid' },
  { id: '152', name: 'Graines de lin', englishName: 'Flax seeds', emoji: '🫙', calories: 534, protein: 18.3, fat: 42.2, carbs: 28.9, servingSize: '100g', type: 'solid' },
  { id: '153', name: 'Graines de courge', englishName: 'Pumpkin seeds', emoji: '🎃', calories: 559, protein: 30.2, fat: 49.1, carbs: 10.7, servingSize: '100g', type: 'solid' },
  { id: '154', name: 'Boulghour (cru)', englishName: 'Bulgur (raw)', emoji: '🌾', calories: 342, protein: 12.3, fat: 1.3, carbs: 75.9, servingSize: '100g', type: 'solid' },
  { id: '155', name: 'Moutarde', englishName: 'Mustard', emoji: '🌭', calories: 66, protein: 4.4, fat: 3.6, carbs: 5.3, servingSize: '100g', type: 'solid' },
  { id: '156', name: 'Sauce soja', englishName: 'Soy sauce', emoji: '🥢', calories: 53, protein: 8.1, fat: 0.0, carbs: 4.9, servingSize: '100ml', type: 'liquid' },
  { id: '157', name: 'Vinaigre balsamique', englishName: 'Balsamic vinegar', emoji: '🫙', calories: 88, protein: 0.5, fat: 0.0, carbs: 23.0, servingSize: '100ml', type: 'liquid' },
  { id: '158', name: 'Vinaigre de cidre', englishName: 'Apple cider vinegar', emoji: '🍎', calories: 21, protein: 0.0, fat: 0.0, carbs: 0.9, servingSize: '100ml', type: 'liquid' },
  { id: '159', name: 'Huile de tournesol', englishName: 'Sunflower oil', emoji: '🌻', calories: 900, protein: 0.0, fat: 100.0, carbs: 0.0, servingSize: '100ml', type: 'liquid' },
  { id: '160', name: 'Huile de coco', englishName: 'Coconut oil', emoji: '🥥', calories: 862, protein: 0.0, fat: 100.0, carbs: 0.0, servingSize: '100g', type: 'solid' },
  { id: '161', name: 'Huile d\'avocat', englishName: 'Avocado oil', emoji: '🥑', calories: 884, protein: 0.0, fat: 100.0, carbs: 0.0, servingSize: '100ml', type: 'liquid' },
  { id: '162', name: 'Huile de sésame', englishName: 'Sesame oil', emoji: '🫙', calories: 884, protein: 0.0, fat: 100.0, carbs: 0.0, servingSize: '100ml', type: 'liquid' },
  { id: '163', name: 'Lait d\'amande (non sucré)', englishName: 'Almond milk (unsweetened)', emoji: '🥛', calories: 15, protein: 0.6, fat: 1.1, carbs: 0.3, servingSize: '100ml', type: 'liquid' },
  { id: '164', name: 'Lait de soja', englishName: 'Soy milk', emoji: '🥛', calories: 45, protein: 3.3, fat: 1.8, carbs: 4.0, servingSize: '100ml', type: 'liquid' },
  { id: '165', name: 'Lait d\'avoine', englishName: 'Oat milk', emoji: '🥛', calories: 50, protein: 1.0, fat: 0.8, carbs: 9.0, servingSize: '100ml', type: 'liquid' },
  { id: '166', name: 'Tofu ferme', englishName: 'Firm tofu', emoji: '🧊', calories: 144, protein: 15.8, fat: 8.7, carbs: 3.9, servingSize: '100g', type: 'solid' },
  { id: '167', name: 'Tempeh', englishName: 'Tempeh', emoji: '🧊', calories: 193, protein: 18.5, fat: 10.8, carbs: 9.4, servingSize: '100g', type: 'solid' },
  { id: '168', name: 'Seitan', englishName: 'Seitan', emoji: '🧊', calories: 370, protein: 75.0, fat: 1.9, carbs: 13.8, servingSize: '100g', type: 'solid' },
  { id: '169', name: 'Miel', englishName: 'Honey', emoji: '🍯', calories: 304, protein: 0.3, fat: 0.0, carbs: 82.4, servingSize: '100g', type: 'solid' },
  { id: '170', name: 'Sirop d\'érable', englishName: 'Maple syrup', emoji: '🍁', calories: 260, protein: 0.0, fat: 0.1, carbs: 67.0, servingSize: '100ml', type: 'liquid' },
  { id: '171', name: 'Chocolat noir (70%)', englishName: 'Dark chocolate (70%)', emoji: '🍫', calories: 598, protein: 7.8, fat: 42.6, carbs: 45.9, servingSize: '100g', type: 'solid' },
  { id: '172', name: 'Chocolat au lait', englishName: 'Milk chocolate', emoji: '🍫', calories: 535, protein: 7.7, fat: 29.7, carbs: 59.4, servingSize: '100g', type: 'solid' },
  { id: '173', name: 'Beurre de cacahuète', englishName: 'Peanut butter', emoji: '🥜', calories: 588, protein: 25.0, fat: 50.0, carbs: 20.0, servingSize: '100g', type: 'solid' },
  { id: '174', name: 'Beurre d\'amande', englishName: 'Almond butter', emoji: '🥜', calories: 614, protein: 21.0, fat: 55.5, carbs: 18.8, servingSize: '100g', type: 'solid' },
  { id: '175', name: 'Houmous', englishName: 'Hummus', emoji: '🥣', calories: 166, protein: 7.9, fat: 9.6, carbs: 14.3, servingSize: '100g', type: 'solid' },
  { id: '176', name: 'Guacamole', englishName: 'Guacamole', emoji: '🥑', calories: 157, protein: 2.0, fat: 14.7, carbs: 8.5, servingSize: '100g', type: 'solid' },
  { id: '177', name: 'Pesto', englishName: 'Pesto', emoji: '🌿', calories: 529, protein: 4.8, fat: 52.0, carbs: 9.8, servingSize: '100g', type: 'solid' },
  { id: '178', name: 'Mayonnaise', englishName: 'Mayonnaise', emoji: '🥣', calories: 680, protein: 1.0, fat: 75.0, carbs: 0.6, servingSize: '100g', type: 'solid' },
  { id: '179', name: 'Ketchup', englishName: 'Ketchup', emoji: '🍅', calories: 112, protein: 1.2, fat: 0.1, carbs: 27.4, servingSize: '100g', type: 'solid' },
  { id: '180', name: 'Confiture de fraises', englishName: 'Strawberry jam', emoji: '🍓', calories: 278, protein: 0.4, fat: 0.1, carbs: 68.9, servingSize: '100g', type: 'solid' },
  { id: '181', name: 'Pain de mie', englishName: 'Sliced bread', emoji: '🍞', calories: 265, protein: 9.0, fat: 3.2, carbs: 49.0, servingSize: '1 slice (25g)', type: 'unit', weightPerUnit: 25 },
  { id: '182', name: 'Biscotte', englishName: 'Rusk', emoji: '🍞', calories: 400, protein: 11.0, fat: 6.0, carbs: 75.0, servingSize: '1 unit (10g)', type: 'unit', weightPerUnit: 10 },
  { id: '183', name: 'Croissant', englishName: 'Croissant', emoji: '🥐', calories: 406, protein: 8.2, fat: 21.0, carbs: 45.8, servingSize: '1 unit (60g)', type: 'unit', weightPerUnit: 60 },
  { id: '184', name: 'Pain au chocolat', englishName: 'Chocolate pastry', emoji: '🥐', calories: 410, protein: 7.5, fat: 22.0, carbs: 46.0, servingSize: '1 unit (70g)', type: 'unit', weightPerUnit: 70 },
  { id: '185', name: 'Madeleine', englishName: 'Madeleine', emoji: '🧁', calories: 446, protein: 6.5, fat: 24.0, carbs: 51.0, servingSize: '1 unit (25g)', type: 'unit', weightPerUnit: 25 },
  { id: '186', name: 'Macaron', englishName: 'Macaron', emoji: '🧁', calories: 450, protein: 7.0, fat: 20.0, carbs: 60.0, servingSize: '1 unit (20g)', type: 'unit', weightPerUnit: 20 },
  { id: '187', name: 'Crêpe (nature)', englishName: 'Crepe (plain)', emoji: '🥞', calories: 220, protein: 7.0, fat: 8.0, carbs: 30.0, servingSize: '1 unit (50g)', type: 'unit', weightPerUnit: 50 },
  { id: '188', name: 'Gaufre', englishName: 'Waffle', emoji: '🧇', calories: 291, protein: 7.9, fat: 14.0, carbs: 33.0, servingSize: '1 unit (80g)', type: 'unit', weightPerUnit: 80 },
  { id: '189', name: 'Pop-corn (nature)', englishName: 'Popcorn (plain)', emoji: '🍿', calories: 375, protein: 12.0, fat: 4.3, carbs: 74.0, servingSize: '100g', type: 'solid' },
  { id: '190', name: 'Chips de pomme de terre', englishName: 'Potato chips', emoji: '🍟', calories: 536, protein: 7.0, fat: 35.0, carbs: 53.0, servingSize: '100g', type: 'solid' },
  { id: '191', name: 'Bretzel', englishName: 'Pretzel', emoji: '🥨', calories: 380, protein: 10.0, fat: 3.0, carbs: 80.0, servingSize: '100g', type: 'solid' },
  { id: '192', name: 'Bière', englishName: 'Beer', emoji: '🍺', calories: 43, protein: 0.5, fat: 0.0, carbs: 3.6, servingSize: '100ml', type: 'liquid' },
  { id: '193', name: 'Vin rouge', englishName: 'Red wine', emoji: '🍷', calories: 85, protein: 0.1, fat: 0.0, carbs: 2.6, servingSize: '100ml', type: 'liquid' },
  { id: '194', name: 'Vin blanc', englishName: 'White wine', emoji: '🥂', calories: 82, protein: 0.1, fat: 0.0, carbs: 2.6, servingSize: '100ml', type: 'liquid' },
  { id: '195', name: 'Champagne', englishName: 'Champagne', emoji: '🍾', calories: 75, protein: 0.3, fat: 0.0, carbs: 1.5, servingSize: '100ml', type: 'liquid' },
  { id: '196', name: 'Vodka', englishName: 'Vodka', emoji: '🥃', calories: 231, protein: 0.0, fat: 0.0, carbs: 0.0, servingSize: '100ml', type: 'liquid' },
  { id: '197', name: 'Whisky', englishName: 'Whisky', emoji: '🥃', calories: 250, protein: 0.0, fat: 0.0, carbs: 0.1, servingSize: '100ml', type: 'liquid' },
  { id: '198', name: 'Rhum', englishName: 'Rum', emoji: '🥃', calories: 231, protein: 0.0, fat: 0.0, carbs: 0.0, servingSize: '100ml', type: 'liquid' },
  { id: '199', name: 'Jus d\'orange', englishName: 'Orange juice', emoji: '🍊', calories: 45, protein: 0.7, fat: 0.2, carbs: 10.4, servingSize: '100ml', type: 'liquid' },
  { id: '200', name: 'Jus de pomme', englishName: 'Apple juice', emoji: '🍎', calories: 46, protein: 0.1, fat: 0.1, carbs: 11.3, servingSize: '100ml', type: 'liquid' },
];
